- src/app/components/dialogs/send-final-result/send-final-result.component.html
- src/app/components/dialogs/send-final-result/send-final-result.component.scss
- src/app/components/dialogs/send-final-result/send-final-result.component.ts
- src/app/models/lobby.ts
- src/app/models/wytournament/wy-tournament.ts
- src/app/modules/irc/components/irc/irc.component.html
- src/app/modules/irc/components/irc/irc.component.ts
- src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
- src/app/modules/tournament-management/components/tournament/tournament-wybin/tournament-wybin.component.html
- src/app/modules/tournament-management/components/tournament/tournament-wybin/tournament-wybin.component.spec.ts
- src/app/modules/tournament-management/components/tournament/tournament-wybin/tournament-wybin.component.ts
- src/app/modules/tournament-management/components/tournament/tournament/tournament.component.html
- src/app/modules/tournament-management/tournament-management.module.ts
Implement a way to connect a wyBin tournament to a wyReferee tournament
When a tournament is linked, it'll update the match score and bans when the final webhook gets sent, as well as update the stats for that match
> wyBin score update

- src/app/services/irc.service.ts
Remove the `Incorrect slot, player should be in slot x` message when it is a qualifier lobby
> Remove incorrect slot message from qualifier lobbies

- .eslintrc.json
- package.json
- src/app/models/score-calculation/calculation-types/axs-calculation.ts
- src/app/models/score-calculation/calculation-types/oml-score-calculation.ts
- src/app/models/score-calculation/calculation-types/score-interface.ts
- src/app/models/score-calculation/calculation-types/team-vs-calculation.ts
- src/app/models/score-calculation/calculation-types/team-vs-hidden-calculation.ts
- src/app/models/score-calculation/calculation-types/three-cwc-score-calculation.ts
- src/app/models/store-multiplayer/multiplayer-data-user.ts
- src/app/models/store-multiplayer/multiplayer-data.ts
- src/app/modules/lobby/components/lobby-view/lobby-view.component.html
- src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
- src/app/services/wy-multiplayer-lobbies.service.ts
- yarn.lock
Scores were being calculated by which slot the players were in. With this it will no longer check (except for AxS) in which slot the players are, but rather which team they are on. This will minimize the risk of people not being in the correct slots and such
> Score interface refactor

- package.json
- src/app/components/dialogs/send-beatmap-result/send-beatmap-result.component.ts
- src/app/models/lobby.ts
- src/app/models/score-calculation/calculate.ts
- src/app/models/score-calculation/calculation-types/ctm-calculation.ts
- src/app/models/score-calculation/calculation-types/score-interface.ts
- src/app/models/store-multiplayer/multiplayer-data.ts
- src/app/models/wytournament/mappool/wy-mappool.ts
- src/app/models/wytournament/mappool/wy-mod-bracket-map.ts
- src/app/models/wytournament/wy-stage.ts
- src/app/modules/irc/components/irc/irc.component.html
- src/app/modules/irc/components/irc/irc.component.scss
- src/app/modules/irc/components/irc/irc.component.ts
- src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
- src/app/modules/tournament-management/components/mappool/mappool/mappool.component.html
- src/app/modules/tournament-management/components/mappool/mappool/mappool.component.ts
- src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.html
- src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.ts
- src/app/modules/tournament-management/components/tournament-edit/tournament-edit.component.ts
- src/app/modules/tournament-management/components/tournament-published-edit/tournament-published-edit.component.ts
- src/app/modules/tournament-management/components/tournament/tournament-beatmap-result/tournament-beatmap-result.component.html
- src/app/modules/tournament-management/components/tournament/tournament-general/tournament-general.component.ts
- src/app/modules/tournament-management/components/tournament/tournament-stages/tournament-stages.component.html
- src/app/modules/tournament-management/components/tournament/tournament-stages/tournament-stages.component.scss
- src/app/modules/tournament-management/components/tournament/tournament-stages/tournament-stages.component.ts
- src/app/services/wy-multiplayer-lobbies.service.ts
Catch The Magic 4 referee helper
- Implement Hitpoints system instead of traditional score system
- The base hitpoints a match starts out with can be set per stage
- Beating a team now removes hitpoints from the opposing team
- The damage that gets dealt can be set per beatmap
- Give additional score to a team based on selected mods, this is only enabled when a beatmap is supposed to deal 6 or 8 damage
- The additional score is capped at 150k
- When Easy is enabled, the additional score is set to 525k and will ignore any other bonus modifiers
- HR gives a bonus score of 50k
- DT gives a bonus score of 75k
- FL gives a bonus score of 100k
- SD gives a bonus score of 150k
- HD does **not** give any extra score
- Added 3 new variables for beatmap result messages to show the hitpoints and …
> Catch The Magic 4

- src/app/modules/irc/components/irc/irc.component.ts
When holding `CTRL`, `SHIFT` or `ALT` when pressing `Arrow Up` or `Arrow Down` it will no longer navigate through the message history
> Ignore navigating through irc message history when holding down modifier keys

- src/app/models/score-calculation/calculation-types/ctm-calculation.ts
- Change max team bonus score from 150000 to 100000
- Change Easy bonus score from 525000 to 500000
- Change Hardrock bonus score from 50000 to 20000
- Change Doubletime bonus score from 75000 to 40000
- Change Flashlight bonus score from 100000 to 80000
- Change Sudden Death bonus score from 150000 to 100000
> Catch The Magic 4 bonus score change

- src/app/models/wytournament/wy-tournament.ts
- src/app/models/wytournament/wy-webhook.ts
- src/app/modules/irc/components/irc/irc.component.html
- src/app/modules/irc/components/irc/irc.component.ts
- src/app/modules/tournament-management/components/tournament-create/tournament-create.component.ts
- src/app/modules/tournament-management/components/tournament-edit/tournament-edit.component.ts
- src/app/modules/tournament-management/components/tournament-published-edit/tournament-published-edit.component.ts
- src/app/modules/tournament-management/components/tournament/tournament-webhook/tournament-webhook.component.html
- src/app/modules/tournament-management/components/tournament/tournament-webhook/tournament-webhook.component.ts
- src/app/services/webhook.service.ts
Implement a button to send the match summary to a Discord webhook
- Shows the title and the multiplayer link of the current match
- Shows the bans of each teams
- Shows the picks of each teams and sort it in the correct pick order
> Match summary webhook

- src/app/modules/tournament-management/components/tournament-published-edit/tournament-published-edit.component.ts
Validators for AxS modifier and CTM damageAmount was in the incorrect place, throwing errors when trying to edit a published tournament when AxS/CTM is used as the mappool type
> Public tournament validators

- src/app/models/wytournament/mappool/wy-mappool.ts
When a mod bracket exists in a mappool but no maps have been added, it was causing issues making you no longer able to type in chat
Added a check to see whether there are maps in the specific mod bracket, if not the mod bracket can be ignored
> Fix acronym check in chat for empty mod brackets

- src/app/modules/irc/components/irc/irc.component.html
- src/app/modules/irc/components/irc/irc.component.ts
- src/app/modules/settings/components/settings/settings.component.html
- src/app/modules/settings/components/settings/settings.component.ts
- src/app/services/generic.service.ts
- src/app/services/irc.service.ts
By default Banchobot messages were being split above the regular irc section
An option has been added that allows you to "disable" this and have it show up in the normal irc chat
> Add option to toggle split Bancho messages

- src/app/services/irc.service.ts
Disabled the check whether players are in the correct slot when `!mp settings` is ran, it shows that players are in the incorrect spots even if they are in the correct spots and the other way around. Will be enabled again once a proper fix has been made
> Disable the check whether players are in the correct slot

- src/app/modules/irc/components/irc/irc.component.html
The following buttons have been hidden in qualifier lobbies:
- The `Ban this beatmap` button
- The `Unban this beatmap` button
- The `Change which team has picked this map` button
> Hide buttons in qualifier lobbies

- src/app/modules/tournament-management/components/tournament-manage/tournament-published-edit/tournament-published-edit.component.ts
Fix the toggle to create a lobby with or without brackets around the team names
> Fix lobby name with brackets not being saved properly

- package.json
- src/app/modules/irc/components/irc/irc.component.ts
Temporarily remove the ban check before picking a map, forgot about tournaments having delayed bans (2nd ban after x points lost), preventing the client from continuing the match because of not enough bans have been banned at the start
> Remove ban check

- package.json
- src/app/modules/tournament-management/components-utility/tournament/tournament-mappool/mappool/mappool.component.ts
Adds the follow mod brackets when generating mod brackets for a mania tournament: 
- Rice - RC
- Long Note - LN
- Hybrid - HB
- Speed Velocity - SV
- Tiebreaker - TB
All mod brackets have Freemod enabled by default
> Add mania template for mod bracket generation

- src/app/components/dialogs/send-final-result/send-final-result.component.ts
- src/app/services/wybin.service.ts
Fixed an issue where it would only update data on the first Qualifier match on wyBin (regardless of which lobby you are refereeing) when you would send the final result in the IRC view
> Fix qualifier lobby not updating properly

- src/app/modules/tournament-management/components-utility/tournament/tournament-access/tournament-access.component.html
Fixes a typo (`Import stages from wyBin` to `Import staff from wyBin`) when importing staff
> Import staff typo

- main.ts
- package.json
- src/app/services/authenticate.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
The osu! authentication link now opens in the user's default browser instead of within the wyReferee application window.
> osu! authentication

- src/app/layout/sidebar/sidebar.component.html
- src/app/layout/sidebar/sidebar.component.scss
- src/app/modules/authentication/components/authentication/authentication.component.html
- src/app/modules/authentication/components/authentication/authentication.component.ts
The background where the user profile is located will be red when not logged in
Show a warning about osu! tourney spectate client when logging in to IRC takes a long time
> Authentication clarification

- src/app/services/wy-multiplayer-lobbies.service.ts
Fixed an issue where synchronization didn't work when the `Invalidate beatmaps` option is set to not invalidate.
> Synchronization fix when `Invalidate beatmaps` is disabled

- src/app/models/wybintournament/wybin-stage.ts
- src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
- src/app/modules/lobby/components/join-lobby/join-lobby.component.ts
- src/app/modules/lobby/components/lobby-form/lobby-form.component.html
- src/app/modules/lobby/components/lobby-form/lobby-form.component.scss
- src/app/modules/lobby/components/lobby-form/lobby-form.component.ts
- Missing stages created in wyReferee now correctly display when linked to a wyBin tournament, even if they are not listed on wyBin.
- Added a toggle to manually input team names when a wyBin tournament is connected, instead of selecting from a match list.
> Custom match creation

- src/app/modules/lobby/components/lobby-form/lobby-form.component.ts
Fixed an issue where if you toggled `Manually enter participant names` on and off, it prevented match creation from the match dropdown list
> Fix match creation after toggling `Manually enter participant names`

- src/app/modules/irc/components/irc/irc.component.html
Displays a message when no players are available to invite, so referees have a better indication of what is happening. 
See #164
> Display message when no players are available to invite

- src/app/modules/lobby/components/lobby-form/lobby-form.component.html
Fixed an issue when toggling the `Qualifier lobby` option combined with the `Manually enter participant name` would show `Team 1` vs `Team 2`, instead of the Qualifier identifier.
> Allow custom qualifier identifier input for wyBin connected tournaments

- package.json
- src/app/app.module.ts
- src/app/components/dialogs/add-bulk-teams-dialog/add-bulk-teams-dialog.component.html
- src/app/components/dialogs/add-bulk-teams-dialog/add-bulk-teams-dialog.component.spec.ts
- src/app/components/dialogs/add-bulk-teams-dialog/add-bulk-teams-dialog.component.ts
- src/app/modules/tournament-management/components-utility/tournament/tournament-participants/tournament-participants.component.html
- src/app/modules/tournament-management/components-utility/tournament/tournament-participants/tournament-participants.component.ts
Add a new dialog that supports adding teams + players at the same time
Supported formats:
- `Team 1, Player 1, 1234567, Player 2, 7654321`
- `Team 2, Player 4, 1234567, Player 5, 7654321, Player 6, 1726354`
- `Team 3, Player 7, 1234567`
- `Team 4`
- `Team 5, Player 8, , Player 9, `
> Add new dialog to bulk add teams with players

- src/app/modules/tournament-management/components-utility/tournament/tournament-mappool/mappool/mappool.component.ts
- src/app/modules/tournament-management/components-utility/tournament/tournament-mappool/mod-bracket/mod-bracket.component.ts
- src/app/modules/tournament-management/components/tournament-manage/tournament-create/tournament-create.component.ts
- src/app/modules/tournament-management/components/tournament-manage/tournament-edit/tournament-edit.component.ts
- src/app/modules/tournament-management/models/mod-bracket-unique-mods-validator.ts
- src/app/modules/tournament-management/services/validation-error.service.ts
Implement mappool mod bracket mods validation, so you can no longer have duplicate mods.
Prevents from having `NoFail + NoFail = Easy` from happening (or whatever other combinations happen)
> Mappool mods validation
