src/app/modules/tournament-management/components/mappool-create/mappool-create.component.ts

fix(mappool): fix deleting a mappool for local tournaments

---

src/app/modules/irc/components/irc/irc.component.ts
src/app/services/irc.service.ts

fix(irc): fix new messages in channels not being highlighted

---

electron-builder.json
package.json
yarn.lock

Fixes MacOS auto update functionality by building both dmg and zip. Due to this issue with https://github.com/electron-userland/electron-builder/issues/2199
Please delete options that are not relevant.

fix(build): fix auto update functionality on mac

---

src/app/models/mutliplayer-lobby-players/multiplayer-lobby-players.ts
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.ts
src/app/services/irc.service.ts
src/app/shared/directives/ng-var.directive.ts
src/app/shared/shared.module.ts

Irc team colour fix

---

src/app/modules/tournament-management/components/mappool-create/mappool-create.component.html
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.scss
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.ts
src/app/modules/tournament-management/components/mappool/mappool/mappool.component.ts
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.html
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.scss
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.ts
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.html
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.scss
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.ts
src/app/shared/pipes/filter-team.pipe.ts
src/app/shared/pipes/filter-tournament.pipe.ts
src/app/shared/shared.module.ts

- Changed collapsing for teams, players, mappools and modbrackets. You can now click on the headers instead of just the button
- Implemented filtering of teams
- Fixed an issue where you couldn't create default brackets for a mappool after deleting a mod bracket

Toggle dropdowns by header + filter teams + fix create default brackets

---

package.json
src/app/components/dialogs/irc-shortcut-dialog/irc-shortcut-dialog.component.ts
src/app/shared/pipes/filter-team.pipe.ts

- Fixed team not being filtered properly 
- Fixed default irc shortcut command for timer (was start instead of timer)

Fix team filtering

---

package.json
src/app/models/wytournament/wy-tournament.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.html
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/modules/tournament-management/components/tournament-create/tournament-create.component.ts
src/app/modules/tournament-management/components/tournament-edit/tournament-edit.component.ts
src/app/modules/tournament-management/components/tournament/tournament-general/tournament-general.component.html
src/app/modules/tournament-management/components/tournament/tournament-general/tournament-general.component.ts

Implement a toggle to add brackets around the team name when creating a lobby
Resolves #18

Create lobby with brackets around team name

---

src/app/modules/lobby/components/create-lobby/create-lobby.component.html
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts

Add /mp/# links to regex when creating a lobby

---

src/app/layout/main/main.component.scss
src/app/layout/sidebar/sidebar.component.html
src/app/layout/sidebar/sidebar.component.scss
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.scss
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.html
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.scss
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.scss

- Minimize the sidebar when the screen is <1200px
- Moved tooltips for picking/banning beatmaps in irc to the side
- Highlight participants/mappool/modbracket headers when you hover over them (was only a cursor change before)

Sidebar and misc styling

---

angular.json
package.json
src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/core/directive/clickable-links.directive.ts
src/app/layout/sidebar/sidebar.component.html
src/app/layout/sidebar/sidebar.component.scss
src/app/layout/sidebar/sidebar.component.ts
src/app/modules/changelog/changelog-routing.module.ts
src/app/modules/changelog/changelog.module.ts
src/app/modules/changelog/components/changelog/changelog.component.html
src/app/modules/changelog/components/changelog/changelog.component.scss
src/app/modules/changelog/components/changelog/changelog.component.spec.ts
src/app/modules/changelog/components/changelog/changelog.component.ts
src/app/services/cache.service.ts
src/app/shared/shared.module.ts
yarn.lock

Visualize a changelog with all the latest updates made, navigate to changelog after each newly added update

Visualize changelog

---

src/app/layout/sidebar/sidebar.component.html
src/app/layout/sidebar/sidebar.component.scss
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss

- Minimize sidebar, extends on hover
- Minimize irc channels, extends on hover
- Condensed irc channels

Mobile friendly

---

angular.json
package.json
src/app/app-routing.module.ts
src/app/layout/sidebar/sidebar.component.scss
src/app/layout/sidebar/sidebar.component.ts
src/app/modules/webhook/components/webhook/webhook.component.html
src/app/modules/webhook/components/webhook/webhook.component.scss
src/app/modules/webhook/components/webhook/webhook.component.spec.ts
src/app/modules/webhook/components/webhook/webhook.component.ts
src/app/modules/webhook/webhook-routing.module.ts
src/app/modules/webhook/webhook.module.ts
src/app/services/webhook.service.ts

Implement webhook customizations for username/avatar, bottom image and footer

Webhook customization

---

src/app/models/score-calculation/calculate.ts
src/app/models/score-calculation/calculation-types/three-cwc-score-calculation.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Implement 3cwc score calculation interface

feat(calculation): implement 3cwc score calculation

---

src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.html
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.ts

Implement bulk player add 
Fixed bulk add team validators

feat(participants): implement bulk player add

---

src/app/modules/settings/components/settings/settings.component.ts
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.html
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.ts
src/app/services/generic.service.ts

Api key validation

---

src/app/modules/irc/components/irc/irc.component.ts

Automatically changes focus to chat input field after pressing any of the irc shortcuts

Focus message send input field after pressing irc shortcut

---

src/app/models/lobby.ts
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
src/app/services/irc.service.ts

Implement a check that shows when a player is in the incorrect slot when running `!mp settings`

Players incorrect slot

---

src/app/components/dialogs/send-beatmap-result/send-beatmap-result.component.ts
src/app/components/dialogs/send-final-result/send-final-result.component.ts
src/app/models/lobby.ts
src/app/modules/lobby/components/lobby-view/lobby-view.component.html
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
src/app/services/webhook.service.ts

Fix that webhooks also account for the overwritten scores

fix(webhook): fix webhook not using the overwrited score

---

src/app/models/irc/regex.ts

Fixed player management not picking up usernames with spaces

fix(regex): fix player management not picking up usernames with spaces

---

main.ts
src/app/app-routing.module.ts
src/app/models/irc/irc-channel.ts
src/app/modules/irc/components/irc-player-management/irc-player-management.component.html
src/app/modules/irc/components/irc-player-management/irc-player-management.component.scss
src/app/modules/irc/components/irc-player-management/irc-player-management.component.spec.ts
src/app/modules/irc/components/irc-player-management/irc-player-management.component.ts
src/app/modules/irc/components/irc-shortcut-commands/irc-shortcut-commands.component.html
src/app/modules/irc/components/irc-shortcut-commands/irc-shortcut-commands.component.scss
src/app/modules/irc/components/irc-shortcut-commands/irc-shortcut-commands.component.spec.ts
src/app/modules/irc/components/irc-shortcut-commands/irc-shortcut-commands.component.ts
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/irc/irc.module.ts
src/app/services/irc.service.ts

- Split up irc component in multiple
- Remove sidebar menu when in irc view
- Move player management below the irc channels
- Split up banchobot & other messages into different chat boxes
- Make divider moveable

IRC redesign

---

src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/services/multiplayer-lobby-players.service.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Fixes the issue when creating a match it wouldn't show the irc view

Irc create match fix

---

src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/services/irc.service.ts
src/app/services/wy-multiplayer-lobbies.service.ts
src/app/shared/components/toast/toast.component.scss

Fixes synchronizing multiplayer lobbies after a map has finished
Add toasts back to irc view

Synchronize fix

---

src/app/components/dialogs/send-beatmap-result/send-beatmap-result.component.ts
src/app/models/wytournament/wy-beatmap-result-message.ts
src/app/models/wytournament/wy-tournament.ts
src/app/modules/tournament-management/components/tournament-edit/tournament-edit.component.ts
src/app/modules/tournament-management/components/tournament-published-edit/tournament-published-edit.component.ts
src/app/modules/tournament-management/components/tournament/tournament-beatmap-result/tournament-beatmap-result.component.html
src/app/modules/tournament-management/components/tournament/tournament-beatmap-result/tournament-beatmap-result.component.scss
src/app/modules/tournament-management/components/tournament/tournament-beatmap-result/tournament-beatmap-result.component.spec.ts
src/app/modules/tournament-management/components/tournament/tournament-beatmap-result/tournament-beatmap-result.component.ts
src/app/modules/tournament-management/components/tournament/tournament/tournament.component.html
src/app/modules/tournament-management/tournament-management.module.ts
src/styles.scss

Implement customization for the message that gets sent when you send the beatmap result of a match

Beatmap result message customization

---

src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/services/tournament.service.ts

Force update the tournaments when you create a lobby

feat(tournament): update all tournaments when creating a lobby

---

package.json
src/app/models/score-calculation/calculate.ts
src/app/models/score-calculation/calculation-types/oml-score-calculation.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Implement OML score calculation with 1.00x for every mod on the Mixed mod bracket

Implement OML score calculation

---

package.json
src/app/models/score-calculation/calculation-types/oml-score-calculation.ts

Update OML score interface for the latest score v2 changes
- Remove HR/etc. scaling
- Set FL scaling to 1.00x

feat(oml): update OML score interface for scorev2 changes

---

src/app/models/osu-models/osu.ts
src/app/models/wytournament/mappool/wy-mappool.ts
src/app/models/wytournament/wy-tournament.ts
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.html
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.scss
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.ts
src/app/services/tournament.service.ts

Implement importing mappools when you have a wyBin tournament connected to your wyReferee tournament.

Implement importing mappools from connected wyBin tournament

---

src/app/models/lobby.ts
src/app/models/wytournament/wy-team-player.ts
src/app/models/wytournament/wy-team.ts
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/tournament-management/components/tournament-edit/tournament-edit.component.ts
src/app/modules/tournament-management/components/tournament-published-edit/tournament-published-edit.component.ts
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.html
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.scss
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.ts

Add user id to all players
Invite button in IRC will first look if the user id is set, if it is it'll invite it with `!mp invite #userid`, if it isn't set it'll invite the player through `!mp invite username`

Add userId to teams/players

---

src/app/models/osu-models/osu.ts
src/app/models/wytournament/mappool/wy-mod-bracket-map.ts
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.html
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.ts
src/app/modules/tournament-management/components/tournament/tournament-general/tournament-general.component.html
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.html
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.scss
src/app/modules/tournament-management/components/tournament/tournament-participants/tournament-participants.component.ts
src/app/modules/tournament-management/components/tournament/tournament/tournament.component.html
src/app/services/tournament.service.ts

Add All modes gamemode type, allows for beatmaps to have a specific gamemode so one map can be osu!, another one osu!catch, etc.

Beatmap gamemode selection

---

src/app/models/osu-models/osu.ts
src/app/models/wytournament/mappool/wy-mod-bracket-map.ts
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.html
src/app/modules/tournament-management/components/mappool/mod-bracket/mod-bracket.component.ts
src/app/modules/tournament-management/components/tournament/tournament-general/tournament-general.component.html
src/app/modules/tournament-management/components/tournament/tournament/tournament.component.html

Implements pre beatmap gamemode, allows for one map to be osu!, another osu!catch, etc.

Implement beatmap gamemode

---

package.json
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts
src/app/services/tournament.service.ts

Add teams that have signed up for the created qualifier lobby. Only works if a wyBin tournament has been selected

Add teams to dropdown for qualifier lobbies

---

package.json
src/app/services/irc.service.ts

Makes the window flash whenever a message gets sent and the window is not focused

Make window flash on irc message

---

package.json
src/app/models/irc/irc-channel.ts
src/app/modules/irc/components/irc/irc.component.ts
src/app/services/irc.service.ts

Allows you to navigate through your last sent messages using Arrow Up and Arrow Down
Closes #67

Irc message history

---

src/app/components/dialogs/send-final-result/send-final-result.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/services/webhook.service.ts
src/app/services/wybin.service.ts

Add casters/streamer Twitch commands to the match creation webhook if wyBin is connected
Closes #66

Match creation staff

---

src/app/models/osu-models/osu.ts
src/app/models/wytournament/mappool/wy-mappool.ts
src/app/models/wytournament/wy-stage.ts
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.html
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.scss
src/app/modules/tournament-management/components/mappool-create/mappool-create.component.ts
src/app/modules/tournament-management/components/tournament/tournament-access/tournament-access.component.html
src/app/modules/tournament-management/components/tournament/tournament-access/tournament-access.component.ts
src/app/modules/tournament-management/components/tournament/tournament-stages/tournament-stages.component.html
src/app/modules/tournament-management/components/tournament/tournament-stages/tournament-stages.component.ts
src/app/services/wybin.service.ts
src/styles.scss

- Implement importing stages from wyBin
- Implement importing tournament access from wyBin
- Fix mappool order when importing mappools from wyBin
- Give Nomod and Mixed Mod the proper abbreviation when importing from wyBin
- Add a Nofail toggle that will add Nofail to all mod brackets when importing from wyBin
- When importing an osu!catch tournament, change some of the mod combinations that gets added
- Hardrock and Mixed mod gets Freemod
- Doubletime gets both Doubletime and Freemod
Closes #69

Import from wybin

---

src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/services/challonge.service.ts
src/app/services/webhook.service.ts

Updates score to Challonge when the tournament has a connected wyBin tournament
Match score gets updated real time and whenever the final result gets sent.
Implements #74

Challonge score integration

---

package.json
src/app/models/irc/irc-message.ts
src/app/models/lobby.ts
src/app/models/slash-command.ts
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/services/slash-command.service.ts

Implement functionality for slash commands
Closes #77

Slash commands

---

src/app/layout/main/main.component.html
src/app/layout/main/main.component.ts
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/tournament-management/components/tournament-edit/tournament-edit.component.html
src/app/modules/tournament-management/components/tournament-published-edit/tournament-published-edit.component.html
src/app/shared/components/debug/debug.component.html
src/app/shared/components/debug/debug.component.scss
src/app/shared/components/debug/debug.component.ts

Reimplement the debug overlay so you can view variables in realtime

Debug overlay

---

src/app/modules/tournament-management/components/tournament/tournament-access/tournament-access.component.html
src/app/modules/tournament-management/components/tournament/tournament-stages/tournament-stages.component.html

Match scores/bans/etc. weren't being updated to the wyBin page, issue was that the stage names did not match. 
Added a few info boxes explaining what to do in order for the matches to update properly

wyBin match update info

---

src/app/layout/sidebar/sidebar.component.html
src/app/layout/sidebar/sidebar.component.scss

Fixes the toggling of the `Hide AxS menu item` button

Fix hide AxS menu item button

---

src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.ts
src/app/services/tournament.service.ts

Implements player inviting for a qualifier lobby for 1v1 tournaments, requires wyBin integration in order for it to work

Qualifier lobby 1v1 player invite

---

src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts

Changed how Challonge score update works, now only updates it after the final result has been sent in instead of every score update

Challonge score update

---

src/app/modules/lobby/components/create-lobby/create-lobby.component.html
src/app/modules/tournament-management/components-utility/tournament/tournament-webhook/tournament-webhook.component.html

- Added extra information for webhooks regarding Qualifiers in the Tournament > Webhooks settings
- Added extra information for webhooks regarding Qualifiers when creating a lobby

Qualifier webhooks explanation

---

src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts

As title describes, adds a button to the invite menu that opens a new dm channel with the player if they don't have it open already
Closes #93

Add a button to open dm channel with a player

---

src/app/modules/information/components/information/information.component.html
src/app/modules/information/components/information/information.component.scss

Adds a scrollbar to information page, closes #99

Add scroll to information page

---

package.json
src/app/services/webhook.service.ts

Centralize the way the webhooks are prevented from being sent depending on various conditions

Centralize send webhook

---

src/app/modules/tournament-management/components-utility/tournament-card/tournament-card.component.html
src/app/modules/tournament-management/components-utility/tournament-card/tournament-card.component.ts
src/app/modules/tournament-management/components/tournament-manage/tournament-edit/tournament-edit.component.html
src/app/modules/tournament-management/components/tournament-manage/tournament-published-edit/tournament-published-edit.component.html
src/app/modules/tournament-management/components/tournament-view/tournament-overview/tournament-overview.component.html
src/app/modules/tournament-management/components/tournament-view/tournament-overview/tournament-overview.component.ts

Update the tournament publishing process
- When a tournament gets published, the local tournament will now be updated to the newly published tournament
- Publish tournament button has been replaced with a "Go to published tournament" button when it has been published 
- Both buttons above have been removed from the published tournaments page
Closes #102

Tournament update clarification

---

src/app/modules/lobby/components/all-lobbies/all-lobbies.component.html
src/app/modules/lobby/components/all-lobbies/all-lobbies.component.scss
src/app/modules/lobby/components/create-lobby/create-lobby.component.html
src/app/services/tutorial.service.ts

Implement the lobby creation tutorial
Closes #105

Lobby creation tutorial

---

src/app/models/wytournament/mappool/wy-mappool.ts

When importing from wyBin, also import the gamemode id for beatmaps when they have been assigned

Import gamemode id for beatmaps

---

package.json
src/app/models/score-calculation/calculation-types/axs-calculation.ts

Hotfixes AxS scoring, somehow uses 0 scores instead of the actual scores due to some bug, will have to fix it properly later

Hotfix axs scoring

---

src/app/models/score-calculation/calculation-types/axs-calculation.ts
src/app/models/score-calculation/calculation-types/score-interface.ts

Properly fix AxS scoring that was changed in #116

Fix AxS scoring

---

src/app/models/score-calculation/calculate.ts
src/app/models/score-calculation/calculation-types/team-vs-dtb-calculation.ts
src/app/modules/lobby/components/lobby-view/lobby-view.component.html
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
src/app/services/webhook.service.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Implements Dodge The Beat scoring 
Mod brackets that are named Dodge The Beat/DodgeTheBeat/DTB (capital insensitive) should be using reverse scoring, ie. lowest score wins.

Dodge the beat score calculation

---

src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss

Fixes the mappool width in the IRC view. 
Long artist/song name/title would not get cut off making the beatmap tiles way too big.

Change mappool resizing

---

src/app/modules/tournament-management/components/tournament-manage/tournament-edit/tournament-edit.component.html
src/app/modules/tournament-management/components/tournament-manage/tournament-edit/tournament-edit.component.scss

Change the Edit tournament indicator to better show whether you are editing the local or public copy of the tournament

Edit tournament indicator

---

src/app/modules/authentication/components/authentication/authentication.component.html
src/app/modules/authentication/components/authentication/authentication.component.ts

Hides the login containers when the user has not entered a valid API key yet.

Hide login containers

---

package.json
src/app/modules/authentication/components/authentication/authentication.component.html
src/app/modules/authentication/components/authentication/authentication.component.ts
src/app/services/irc.service.ts

- Fixed an issue that if a user has a space in their username it doesn't let them login (had to replace the space with an underscore manually)
- Added error logging for when you failed to login
Closes #131

Irc authentication

---

package.json
src/app/modules/lobby/components/create-lobby/create-lobby.component.html
src/app/modules/lobby/components/create-lobby/create-lobby.component.scss
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/modules/lobby/components/join-lobby/join-lobby.component.html
src/app/modules/lobby/components/join-lobby/join-lobby.component.scss
src/app/modules/lobby/components/join-lobby/join-lobby.component.ts

Joining a lobby would sometimes not work, this should now be fixed.
Also added an indicator that shows you when you are either joining or creating a new multiplayer lobby

Join lobby fix

---

src/app/models/calculations.ts

Implemented Taiko accuracy so it shows the correct accuracy for webhooks and in-game results

Implement Taiko accuracy

---

src/app/services/webhook.service.ts

Usernames that contain an underscore (`_`) no longer mess up the formatting in the webhooks
Add a no streamer/caster available message to the match creation webhook

Webhook fixes

---

src/app/models/calculations.ts

Implemented osu! accuracy calculations

osu! accuracy calculation

---

src/app/services/irc.service.ts

Changed the time format so it also includes seconds (HH:MM:SS)

IRC chat change time format

---

src/app/models/sidebar-item.ts
src/app/modules/tournament-management/components-utility/tournament-card/tournament-card.component.html
src/app/modules/tournament-management/components-utility/tournament-card/tournament-card.component.ts
src/app/modules/tournament-management/components/management-router/management-router.component.html
src/app/modules/tournament-management/components/management-router/management-router.component.ts
src/app/modules/tournament-management/components/tournament-view/tournament-overview/tournament-overview.component.html
src/app/modules/tournament-management/components/tournament-view/tournament-overview/tournament-overview.component.ts

- Hide `All tournaments` button when not logged in
- Hide `my published tournaments` when not logged in
- Hide `Go to published tournament` button when not logged in

Tournament management logged in changes

---

src/app/modules/information/components/information/information.component.html
src/app/modules/information/components/information/information.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Added a link to the Discord server to the information page

Add Discord link to information

---

src/app/components/dialogs/send-final-result/send-final-result.component.ts
src/app/models/lobby.ts
src/app/models/wybintournament/wybin-match.ts
src/app/models/wybintournament/wybin-opponent.ts
src/app/models/wybintournament/wybin-stage.ts
src/app/models/wytournament/wy-stage.ts
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/modules/lobby/components/join-lobby/join-lobby.component.ts
src/app/modules/lobby/components/lobby-form/lobby-form.component.html
src/app/modules/lobby/components/lobby-form/lobby-form.component.scss
src/app/modules/lobby/components/lobby-form/lobby-form.component.ts
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
src/app/services/challonge.service.ts
src/app/services/tournament.service.ts
src/app/services/wybin.service.ts

When a wyBin tournament is connected to a wyReferee tournament, a list with matches will now be shown that you can select from.
If no wyBin tournament is connected, you will have to select opponent one and two like you always used to.

Lobby creation

---

package.json
src/app/models/wybintournament/wybin-stage.ts

Fix an issue that prevents the referee from creating a lobby for 1v1 tournaments when a wyBin tournament is connected

Fix not being able to create lobby for 1v1 tournament

---

src/app/components/dialogs/send-beatmap-result/send-beatmap-result.component.html
src/app/components/dialogs/send-beatmap-result/send-beatmap-result.component.ts
src/app/models/lobby.ts
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/modules/lobby/components/lobby-form/lobby-form.component.ts
src/app/modules/lobby/components/lobby-view/lobby-view.component.html
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
src/app/services/cache.service.ts

Added a results dialog that appears when:
- A beatmap finishes
- A match finishes
This makes it easier to send beatmap or match results

IRC dialog with match status updates

---

src/app/modules/tournament-management/components-utility/tournament/tournament-mappool/mappool-overview/mappool-overview.component.ts
src/app/modules/tournament-management/components-utility/tournament/tournament-wybin/tournament-wybin.component.html
src/app/modules/tournament-management/components-utility/tournament/tournament-wybin/tournament-wybin.component.ts

Fixed an issue where deleting a mappool after creating it prevented the tournament from being finalized.
Added search bar for wyBin tournaments

Creating tournament after deleting mappool

---

src/app/models/lobby.ts
src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.scss
src/app/modules/irc/components/irc/irc.component.ts
src/app/modules/lobby/components/lobby-view/lobby-view.component.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Moved the various settings in the IRC screen's sidebar into separate tabs.

IRC sidebar rework

---

src/app/models/wytournament/wy-tournament.ts
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/modules/tournament-management/components-utility/tournament/tournament-general/tournament-general.component.html
src/app/modules/tournament-management/components/tournament-manage/tournament-create/tournament-create.component.ts
src/app/modules/tournament-management/components/tournament-manage/tournament-edit/tournament-edit.component.ts
src/app/modules/tournament-management/services/validation-error.service.ts

Added Team Mode, Win Condition, and Player settings to tournaments. When a new lobby is created, it will automatically use the tournament's settings.

Lobby creation default settings

---

package.json
src/app/models/osu-models/osu.ts

Added additional abbreviations for mod acronyms and a fallback to the mod bracket name.

Abbrevation mappool import fix

---

src/app/models/lobby.ts
src/app/models/wybintournament/wybin-match.ts
src/app/modules/lobby/components/all-lobbies/all-lobbies.component.html
src/app/modules/lobby/components/create-lobby/create-lobby.component.ts
src/app/modules/lobby/components/join-lobby/join-lobby.component.ts
src/app/modules/tournament-management/components-utility/tournament/tournament-general/tournament-general.component.html
src/app/modules/webhook/components/webhook/webhook.component.ts
src/app/services/webhook.service.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Fixed grammar issues, every instance of `vs` is now renamed to `vs.`

Change vs to vs.

---

src/app/modules/irc/components/irc/irc.component.ts

Removed spaces when you select a slash command

Remove space before slash command

---

src/app/models/wytournament/wy-conditional-message.ts
src/app/models/wytournament/wy-tournament.ts

Now properly shows the winner when reverse score is used for a beatmap. 
Fixes #159

Show the proper winner when reverse score is used

---

src/app/modules/irc/components/irc/irc.component.html
src/app/modules/irc/components/irc/irc.component.ts

Adds a message when the multiplayer room settings have been changed, which shows a timer counting down from 3 to 1 before the room gets updated.

Add message when updating multiplayer room settings

---

src/app/modules/lobby/components/lobby-form/lobby-form.component.html
src/app/modules/lobby/components/lobby-form/lobby-form.component.ts

When no tournament is selected, you can now select the Qualifier lobby option to create a qualifier lobby instead of a team vs team lobby

Add qualifier lobby creation when no tournament is selected

---

package.json
src/app/models/calculations.ts
src/app/services/wy-multiplayer-lobbies.service.ts

Fixed an issue where accuracy was always calculated with the osu!catch accuracy formula.

Fix accuracy for non-osu!catch gamemodes
